### ISSUE TITLE
production mode available?

### ISSUE THREAD

**Issue by x4080** [tomastrajan/react-typescript-webpack#1]
Hi, nice work and I love the no flux thing, how can I build production build with it?

**Comment by tomastrajan** [comment]
Hi, right now, prod build just skips generation of source maps but it doesnt minify the sources. There was a reason for it but I don't remember anymore. Will check it out, soon.  Also would be great to add mocha tests for services & mochify / karma integration tests for the components.

**Comment by x4080** [comment]
Ok cool

**Comment by tomastrajan** [comment]
I added more extensive description of available build targets to [README.md](https://github.com/tomastrajan/react-typescript-webpack/blob/master/README.md) and re-enabled code mangling for `prod` build, now it just works.

**Comment by tomastrajan** [comment]
Anyway, if you use it, it would be great if you added mocha & mocha unit tests (mostly for service logic) and submitted a PR ;)
